### ISSUE TITLE
Configuration for .deps/fsi/PxlLocalDev.fsx ?

### ISSUE THREAD

**Issue by CodeMan99** [CuminAndPotato/pxl-playground#2]
I am not an electron dev. I do not have node.js install on my development box.

I built the simulator application in a docker container. Then start the built `.AppImage` on my host machine.

This means the requests to `localhost:5001` are refused when running any "fsi" script.

**Comment by CodeMan99** [comment]
Alright, I've since been able to get requests to reach the server.

1. Modify server to listen on `0.0.0.0`.
2. Build and run application.
3. Open firewall port 5001.
4. Edit .fsx script to set the base url.

```fsharp
open FsHttp

GlobalConfig.defaults
|> Config.useBaseUrl "http://172.17.0.1:5001"
|> GlobalConfig.set
```

Note that `172.17.0.1` is specific to my (docker) setup.

---

I'm now getting new response errors.

```
Error in flushing Canvas. Waiting 2000ms before retrying. (Ex: StatusCodeExpectedxception
  { expected =
     [OK; Created; Accepted; NonAuthoritativeInformation; NoContent;
      ResetContent; PartialContent; MultiStatus; AlreadyReported; 209; 210; 211;
      212; 213; 214; 215; 216; 217; 218; 219; 220; 221; 222; 223; 224; 225;
      IMUsed; 227; 228; 229; 230; 231; 232; 233; 234; 235; 236; 237; 238; 239;
      240; 241; 242; 243; 244; 245; 246; 247; 248; 249; 250; 251; 252; 253; 254;
      255; 256; 257; 258; 259; 260; 261; 262; 263; 264; 265; 266; 267; 268; 269;
      270; 271; 272; 273; 274; 275; 276; 277; 278; 279; 280; 281; 282; 283; 284;
      285; 286; 287; 288; 289; 290; 291; 292; 293; 294; 295; 296; 297; 298; 299]
    actual = NotFound })
```

I have zero clue how to debug this.

**Comment by CodeMan99** [comment]
For what it is worth... I am able to manually "push" frames to the simulator.

```shell
curl -X POST \
     -H 'Content-Type: application/octet-stream' \
     --data-binary "@frames.bin" \
     'http://localhost:5001/pushFrames'
```

**Comment by CodeMan99** [comment]
It's possible a leading slash in the request causing the 404 response? As in `/http://...`

**Comment by SchlenkR** [comment]
Hello and thanks for your interesting posts :) 

For this jam, the only use case we support is having node installed locally (I updated the readme - thank you for pointing that issue) and run the scripts against the locally running simulator. After having node installed, it should work out of the box as explained. Feel free to post here in any case. 

Thanks again, and happy coding :)

**Comment by CodeMan99** [comment]
Well that's a shame.

I would be happy to help create a [devcontainer](https://containers.dev) (or see [vscode docs](https://code.visualstudio.com/docs/devcontainers/containers)) if there's any desire. Of course that means sorting out the related communication issue(s) described here.

Merry Christmas.
